CREATE TABLE IF NOT EXISTS attendance_session (
    session_id TEXT PRIMARY KEY,
    created_by TEXT NOT NULL,
    otp TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expire_at TEXT NOT NULL
);

ALTER TABLE IT_Attendance_2024_2028
ADD COLUMN status TEXT NOT NULL DEFAULT 'ABSENT';

ALTER TABLE IT_Attendance_2025_2029
ADD COLUMN status TEXT NOT NULL DEFAULT 'ABSENT';