import { useRef, useState } from 'react'
import { XIcon, UploadIcon, CheckIcon, AlertIcon } from '../Icons'
import { parseImportFile, validateStaffRows } from '../../utils/adminImport'
import { createAdminStaff } from '../../api/adminApi'
import { ALLOWED_SECTIONS } from '../../utils/sectionValidation'
import ImportPreviewTable from './ImportPreviewTable'
import ManualRowEditor from './ManualRowEditor'
import InitialPasswordNotice from './InitialPasswordNotice'

/*
 * Staff live in one table per department, but an advisor is scoped to a cohort, so
 * the batch chosen on the page is sent with the rows and is what an advisor row is
 * assigned to by default. The staff ID is generated by the server and is not
 * offered here, because it has to stay numeric for the staff-ID sign-in path.
 */

const PREVIEW_COLUMNS = [
  { key: 'staff_name', label: 'Name', bold: true },
  { key: 'email', label: 'Email', monospace: true },
  { key: 'advisor_year', label: 'Advisor year' },
  { key: 'advisor_section', label: 'Advisor section' },
  { key: 'advisor_batch', label: 'Advisor batch' },
]

const MANUAL_COLUMNS = [
  { key: 'staff_name', label: 'Name', required: true },
  { key: 'email', label: 'Email', required: true },
  { key: 'advisor_year', label: 'Advisor year', type: 'number', placeholder: '1-4' },
  { key: 'advisor_section', label: 'Advisor section', type: 'select', options: ['', ...ALLOWED_SECTIONS] },
]

const emptyStaff = () => ({
  staff_name: '',
  email: '',
  advisor_year: '',
  advisor_section: '',
  advisor_batch: '',
})

export default function AddStaffModal({ department, batch, onClose, onImported }) {
  const [mode, setMode] = useState('upload')
  const [fileName, setFileName] = useState('')
  const [fileError, setFileError] = useState('')
  const [validation, setValidation] = useState(null)
  const [manualRows, setManualRows] = useState([emptyStaff()])
  const [submitting, setSubmitting] = useState(false)
  const [submitError, setSubmitError] = useState(null)
  const [result, setResult] = useState(null)
  const [dragOver, setDragOver] = useState(false)
  const fileInputRef = useRef(null)

  const batchKey = batch?.key || ''
  const batchLabel = batch?.label || batchKey

  const handleFile = async (file) => {
    setFileError('')
    setSubmitError(null)
    setValidation(null)
    setResult(null)
    setFileName('')

    const parsed = await parseImportFile(file)
    if (parsed.error) {
      setFileError(parsed.error)
      return
    }

    setFileName(file.name)
    setValidation(validateStaffRows(parsed.rows))
  }

  const handleFileInput = (event) => {
    const file = event.target.files?.[0]
    if (file) handleFile(file)
    event.target.value = ''
  }

  const handleDrop = (event) => {
    event.preventDefault()
    setDragOver(false)
    const file = event.dataTransfer?.files?.[0]
    if (file) handleFile(file)
  }

  /*
   * A row only becomes an advisor when a year and a section are both given, and
   * then it is assigned to the cohort chosen on the page. The batch is not typed:
   * the admin picked it one screen earlier, and a free-text batch here would allow
   * an advisor to be attached to a cohort that does not exist.
   */
  const buildManualRows = () =>
    manualRows
      .map((row) => {
        const year = row.advisor_year === '' ? '' : Number(row.advisor_year)
        const section = String(row.advisor_section || '').trim().toUpperCase()
        const isAdvisor = section !== '' && year !== '' && !Number.isNaN(year)
        return {
          staff_name: row.staff_name,
          email: row.email,
          advisor_year: isAdvisor ? year : '',
          advisor_section: isAdvisor ? section : '',
          advisor_batch: isAdvisor ? batchKey : '',
        }
      })
      .filter((row) => Object.values(row).some((value) => String(value ?? '').trim() !== ''))

  const manualValidation = (() => {
    if (mode !== 'manual') return null
    const rows = buildManualRows()
    if (rows.length === 0) return null
    return validateStaffRows(rows)
  })()

  const activeValidation = mode === 'upload' ? validation : manualValidation

  const handleSubmit = async () => {
    const rows = activeValidation?.validRows
    if (!rows || rows.length === 0) return
    setSubmitting(true)
    setSubmitError(null)
    try {
      const data = await createAdminStaff(department, batchKey, rows)
      setResult(data)
    } catch (err) {
      setSubmitError(err)
    } finally {
      setSubmitting(false)
    }
  }

  const switchMode = (next) => {
    setMode(next)
    setSubmitError(null)
    setResult(null)
    if (next === 'manual') {
      setValidation(null)
      setFileName('')
      setFileError('')
    }
  }

  const renderFilePicker = () => (
    <div>
      <div
        className={`admin-dropzone ${dragOver ? 'admin-dropzone-active' : ''}`}
        onDragOver={(e) => {
          e.preventDefault()
          setDragOver(true)
        }}
        onDragLeave={() => setDragOver(false)}
        onDrop={handleDrop}
      >
        <input
          ref={fileInputRef}
          type="file"
          accept=".csv,.xlsx"
          onChange={handleFileInput}
          className="hidden"
          aria-label="Upload staff list file"
        />
        <button
          type="button"
          onClick={() => fileInputRef.current?.click()}
          className="flex flex-col items-center gap-2 text-center"
        >
          <span className="admin-dropzone-icon">
            <UploadIcon size={22} />
          </span>
          <span className="text-sm font-bold text-slate-700">
            {fileName || 'Click to choose or drag a file here'}
          </span>
          <span className="text-xs text-slate-400">
            CSV or Excel (.xlsx) with columns:{' '}
            <span className="font-semibold text-slate-500">staff_name, email</span>
          </span>
        </button>
      </div>

      {fileError && (
        <div
          role="alert"
          className="mt-3 flex items-start gap-2 rounded-xl border border-amber-200 bg-amber-50 px-4 py-3 text-sm font-medium text-amber-800"
        >
          <AlertIcon size={16} className="mt-0.5 shrink-0" />
          {fileError}
        </div>
      )}

      <div className="mt-3 rounded-xl border border-slate-200 bg-slate-50 p-3">
        <p className="mb-1.5 text-xs font-bold uppercase tracking-wider text-slate-500">
          Column details
        </p>
        <ul className="space-y-1">
          <li className="flex items-baseline gap-2 text-xs text-slate-600">
            <code className="shrink-0 rounded bg-slate-200/70 px-1.5 py-0.5 font-bold text-slate-700">
              staff_name
            </code>
            <span>Full name of the staff member</span>
          </li>
          <li className="flex items-baseline gap-2 text-xs text-slate-600">
            <code className="shrink-0 rounded bg-slate-200/70 px-1.5 py-0.5 font-bold text-slate-700">
              email
            </code>
            <span>Valid staff email address. Also the login name.</span>
          </li>
          <li className="flex items-baseline gap-2 text-xs text-slate-600">
            <code className="shrink-0 rounded bg-slate-200/70 px-1.5 py-0.5 font-bold text-slate-700">
              advisor_year, advisor_section
            </code>
            <span>
              Optional. Set both to make this person the class advisor for {department}{' '}
              {batchLabel}; leave blank for staff who do not hold a class.
            </span>
          </li>
        </ul>
        <p className="mt-2 text-xs font-semibold text-slate-500">
          Department is set to {department}. The staff ID is generated automatically. A login account
          is created for each person you add.
        </p>
      </div>
    </div>
  )

  const renderValidation = () => {
    if (!activeValidation) return null
    if (activeValidation.missingColumns.length > 0) {
      return (
        <div
          role="alert"
          className="mt-4 flex items-start gap-2 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm font-medium text-red-700"
        >
          <AlertIcon size={16} className="mt-0.5 shrink-0" />
          <div>
            <p className="font-bold">The file is missing required columns.</p>
            <p className="mt-1 text-red-600">
              Missing: {activeValidation.missingColumns.join(', ')}. Add these columns to your file
              and upload again.
            </p>
          </div>
        </div>
      )
    }

    return (
      <div className="mt-4 space-y-4">
        <div className="grid grid-cols-2 gap-3 sm:grid-cols-4">
          <div className="admin-import-stat admin-import-stat-total">
            <span className="admin-import-stat-value">{activeValidation.total}</span>
            <span className="admin-import-stat-label">Total rows</span>
          </div>
          <div className="admin-import-stat admin-import-stat-valid">
            <span className="admin-import-stat-value">{activeValidation.validRows.length}</span>
            <span className="admin-import-stat-label">Valid rows</span>
          </div>
          <div className="admin-import-stat admin-import-stat-invalid">
            <span className="admin-import-stat-value">{activeValidation.invalidRows.length}</span>
            <span className="admin-import-stat-label">Invalid rows</span>
          </div>
          <div className="admin-import-stat admin-import-stat-dup">
            <span className="admin-import-stat-value">{activeValidation.duplicateEmails.length}</span>
            <span className="admin-import-stat-label">Duplicate emails</span>
          </div>
        </div>

        {activeValidation.invalidRows.length > 0 && (
          <div className="rounded-xl border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-800">
            <p className="font-bold">
              {activeValidation.invalidRows.length} row
              {activeValidation.invalidRows.length === 1 ? '' : 's'} will be skipped:
            </p>
            <ul className="mt-1.5 max-h-32 space-y-1 overflow-y-auto text-xs">
              {activeValidation.invalidRows.slice(0, 12).map((row) => (
                <li key={row.rowNumber}>
                  Row {row.rowNumber} — <span className="font-bold">{row.reason}</span>
                </li>
              ))}
            </ul>
          </div>
        )}

        {activeValidation.validRows.length > 0 && (
          <>
            <div className="flex items-center gap-2 text-sm font-bold text-slate-700">
              <CheckIcon size={16} className="text-emerald-500" />
              Preview of {activeValidation.validRows.length} valid row
              {activeValidation.validRows.length === 1 ? '' : 's'}
            </div>
            <ImportPreviewTable kind="staff" rows={activeValidation.validRows} columns={PREVIEW_COLUMNS} />
          </>
        )}
      </div>
    )
  }

  const renderResult = () => (
    <div className="mt-4 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-800">
      <div className="flex items-center gap-2 font-bold">
        <CheckIcon size={16} />
        Import complete
      </div>
      <ul className="mt-1.5 space-y-0.5 text-xs">
        <li>
          <span className="font-bold">{result.created || 0}</span> staff member
          {result.created === 1 ? '' : 's'} added to {department}.
        </li>
        <li>
          <span className="font-bold">{result.authAccountsCreated || 0}</span> login account
          {result.authAccountsCreated === 1 ? '' : 's'} created.
        </li>
        <li>
          <span className="font-bold">{result.skipped || 0}</span> already existed and{' '}
          {result.skipped === 1 ? 'was' : 'were'} skipped.
        </li>
        {result.invalid?.length > 0 && (
          <li>
            <span className="font-bold">{result.invalid.length}</span> invalid rows skipped.
          </li>
        )}
        {result.duplicates?.length > 0 && (
          <li>
            <span className="font-bold">{result.duplicates.length}</span> duplicate rows in the file
            skipped.
          </li>
        )}
      </ul>

      {/*
        Only when accounts were actually created. Re-importing a file that already
        exists creates nothing, and telling the admin to hand out a password for
        accounts that were not made would be actively misleading.
      */}
      {result.authAccountsCreated > 0 && (
        <InitialPasswordNotice
          password={result.defaultPassword}
          tone="success"
          className="mt-3"
        />
      )}
    </div>
  )

  const renderModeTabs = () => (
    <div className="flex gap-2" role="tablist" aria-label="How to add staff">
      <button
        type="button"
        role="tab"
        aria-selected={mode === 'upload'}
        onClick={() => switchMode('upload')}
        className={`btn-cf-outline px-3 py-1.5 text-sm ${mode === 'upload' ? 'ring-2 ring-blue-500' : ''}`}
      >
        Upload a file
      </button>
      <button
        type="button"
        role="tab"
        aria-selected={mode === 'manual'}
        onClick={() => switchMode('manual')}
        className={`btn-cf-outline px-3 py-1.5 text-sm ${mode === 'manual' ? 'ring-2 ring-blue-500' : ''}`}
      >
        Enter by hand
      </button>
    </div>
  )

  return (
    <div className="admin-modal-backdrop" role="dialog" aria-modal="true" aria-label="Add staff">
      <div className="admin-modal max-w-4xl">
        <div className="flex items-start justify-between gap-3 border-b border-slate-200 px-5 py-4">
          <div>
            <h2 className="text-lg font-extrabold tracking-tight text-slate-900">
              Add Staff — {department}
            </h2>
            <p className="mt-0.5 text-sm text-slate-500">
              Upload a CSV/Excel file, or type the records in yourself. An advisor row is assigned to{' '}
              {batchLabel}.
            </p>
          </div>
          <button type="button" onClick={onClose} className="admin-modal-close" aria-label="Close">
            <XIcon size={18} />
          </button>
        </div>

        <div className="space-y-4 p-5">
          {!result && renderModeTabs()}

          {/* Stated before importing, so the password is known up front. */}
          {!result && <InitialPasswordNotice />}

          {!result && mode === 'upload' && renderFilePicker()}

          {!result && mode === 'manual' && (
            <>
              <p className="text-sm text-slate-600">
                Leave the advisor columns blank for staff who do not hold a class. Anyone marked as
                an advisor of {batchLabel} gets the class-advisor tools.
              </p>
              <ManualRowEditor
                columns={MANUAL_COLUMNS}
                rows={manualRows}
                onChange={setManualRows}
                makeEmptyRow={emptyStaff}
                addLabel="Add another staff member"
                rowLabel="Staff"
              />
            </>
          )}

          {!result && renderValidation()}

          {submitError && (
            <div
              role="alert"
              className="flex items-start gap-2 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm font-medium text-red-700"
            >
              <AlertIcon size={16} className="mt-0.5 shrink-0" />
              {submitError.message}
            </div>
          )}

          {result && renderResult()}
        </div>

        <div className="flex items-center justify-end gap-2 border-t border-slate-200 bg-slate-50/60 px-5 py-4">
          {result ? (
            <button
              type="button"
              onClick={() => {
                onClose()
                if (onImported) onImported(result)
              }}
              className="btn-cf-primary inline-flex items-center gap-2 px-4 py-2 text-sm"
            >
              Done
            </button>
          ) : (
            <>
              <button type="button" onClick={onClose} className="btn-cf-outline px-4 py-2 text-sm">
                Cancel
              </button>
              <button
                type="button"
                onClick={handleSubmit}
                disabled={submitting || !activeValidation || activeValidation.validRows.length === 0}
                className="btn-cf-primary inline-flex items-center gap-2 px-4 py-2 text-sm"
              >
                {submitting && <span className="cf-spinner" role="status" aria-hidden="true" />}
                {submitting
                  ? 'Importing…'
                  : `Import ${activeValidation?.validRows?.length || 0} staff member${
                      activeValidation?.validRows?.length === 1 ? '' : 's'
                    }`}
              </button>
            </>
          )}
        </div>
      </div>
    </div>
  )
}
