-- Semester support is deliberately additive.  Existing subject and attendance
-- tables are retained because their numeric subject_id values are local to a
-- batch table and may be referenced by historical attendance.

create table if not exists public.semester_subjects (
  id bigint generated by default as identity primary key,
  semester integer not null check (semester between 1 and 8),
  subject_code text not null check (btrim(subject_code) <> ''),
  subject_name text not null check (btrim(subject_name) <> ''),
  created_at timestamptz not null default now(),
  unique (semester, subject_code)
);
create index if not exists semester_subjects_semester_idx on public.semester_subjects (semester);

create table if not exists public.academic_batches (
  id bigint generated by default as identity primary key,
  department text not null check (btrim(department) <> ''),
  batch_code text not null check (batch_code ~ '^[0-9]{4}_[0-9]{4}$'),
  current_semester integer check (current_semester between 1 and 8),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (department, batch_code)
);

-- Discover existing batch tables without deriving a semester from a student's
-- year.  The semester remains NULL until an administrator explicitly selects it.
insert into public.academic_batches (department, batch_code)
select upper((regexp_match(tablename, '^([a-z0-9]+)_students_([0-9]{4}_[0-9]{4})$'))[1]),
       (regexp_match(tablename, '^([a-z0-9]+)_students_([0-9]{4}_[0-9]{4})$'))[2]
from pg_catalog.pg_tables
where schemaname = 'public'
  and tablename ~ '^[a-z0-9]+_students_[0-9]{4}_[0-9]{4}$'
on conflict (department, batch_code) do nothing;

alter table public.semester_subjects enable row level security;
alter table public.academic_batches enable row level security;
drop policy if exists "authenticated_read_semester_subjects" on public.semester_subjects;
create policy "authenticated_read_semester_subjects" on public.semester_subjects
  for select to authenticated using (true);
drop policy if exists "authenticated_read_academic_batches" on public.academic_batches;
create policy "authenticated_read_academic_batches" on public.academic_batches
  for select to authenticated using (true);

-- Snapshot the selected master subject on new attendance.  These nullable,
-- additive columns never rewrite prior rows.  They make future reports stable
-- even after a batch advances to a different semester.
alter table public.attendance_sessions add column if not exists batch_code text;
alter table public.attendance_sessions add column if not exists semester_subject_id bigint;
alter table public.attendance_sessions add column if not exists subject_code text;
alter table public.attendance_sessions add column if not exists subject_name text;
alter table public.attendance_sessions add column if not exists semester integer;

do $$
declare tbl text;
begin
  for tbl in select tablename from pg_catalog.pg_tables
    where schemaname = 'public' and tablename ~ '^[a-z0-9]+_attendance(_[0-9]{4}_[0-9]{4})?$'
  loop
    execute format('alter table public.%I add column if not exists semester_subject_id bigint', tbl);
    execute format('alter table public.%I add column if not exists subject_code text', tbl);
    execute format('alter table public.%I add column if not exists subject_name text', tbl);
    execute format('alter table public.%I add column if not exists semester integer', tbl);
  end loop;
end $$;
